version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: wirelessdb-clickhouse-server
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - /home/data/nvidia/ch_data:/var/lib/clickhouse
      - /home/data/nvidia/ch_logs:/var/log/clickhouse-server
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: wirelessdb-grafana
    ports:
      - "9001:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-config:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
